### PR TITLE
IE style

### LINKED ISSUE #307: Site does not load in Edge (or Firefox) running on Windows 10
When attempting to view the iSearch site both CI & Prod:
+ https://s3-eu-west-1.amazonaws.com/www.tcdl.io/isearch/prod/index.html 
+ https://s3-eu-west-1.amazonaws.com/www.tcdl.io/isearch/0.18/index.html

Sam from SE saw the following error:
ie-error

They error _code_ he saw was `403` and he sent us the debug output: https://gist.github.com/nelsonic/3df838011a5ecf1f05c9ca6e953083c8

### PR DESCRIPTION
**Pull request by Kumjami**
Fixed some styles at IE. 
- Tiles images
- Visited articles add tag button
- Article images

closes #307

### CODE REVIEW

**Comment by tomgco** [comment]
@nelsonic Is it possible to have some regression tests around this with the tests that you have been working on?

**Comment by Kumjami** [comment]
I have just realized that top bar is missing from IE, so im fixing it right now.

**Comment by Kumjami** [comment]
ready!

**Comment by nelsonic** [comment]
@tomgco good point. not yet. let's add them tomorrow morning. 👍

**Comment by Kumjami** [comment]
closes #307

**Comment by tomgco** [comment]
@Kumjami It looks like you have some conflicts in your branch, let @nelsonic or me know when it is fixed.

**Pull request merged**
