### PR TITLE
Autocompletefocus

### PR DESCRIPTION
**Pull request by Kumjami**
On focus:
image

When there is no results: 

image

On hover: 

image

When text is more than one line (working on that): 

image

### CODE REVIEW

**Comment by lennym** [comment]
I've found a little UI bug in the search box that I'm just looking into on master before reporting.

* Search for a tag
* Click reset
* Type in search box

Then search box becomes unresponsive to typing, and assorted javascript errors are displayed in console.

**Comment by lennym** [comment]
It might be cool now we're collecting data to use our analytics/ranking services to provide the actual most popular tags too rather than a hardcoded list.

**Comment by tomgco** [comment]
> It might be cool now we're collecting data to use our analytics/ranking services to provide the actual most popular tags too rather than a hardcoded list.

Let's get this merged first :D

**Comment by tomgco** [comment]
> I've found a little UI bug in the search box that I'm just looking into on master before reporting.
> 
> Search for a tag
> Click reset
> Type in search box
> Then search box becomes unresponsive to typing, and assorted javascript errors are displayed in console.
> 
> Edit: this works fine on master, and is reproducible on this branch with the steps above.

@Kumjami Can you reproduce and fix the following bug, once done we can merge this in :]

**Comment by Kumjami** [comment]
@tomgco Working on it, actually this concrete bug is fixed but I want to improve a little bit user experience.

While searching for something, the previous suggestions are there to the onfocus, and other details

**Comment by lennym** [comment]
@tomgco I agree.

**Comment by Kumjami** [comment]
@lennym @tomgco review/merge pls
thanks

**Comment by tomgco** [comment]
@Kumjami Isn't this merging into the wrong branch? 

`Kumjami  wants to merge 6 commits into autosuggestDefault from autocompletefocus`

**Comment by Kumjami** [comment]
this would be merge with @jackcarlisle branch, and then @jackcarlisle branch could be merge to master 
this branch was created from @jackcarlisle´s one

**Pull request merged**
