### PR TITLE
Reduce binary size from 2MB to ~800KB

### PR DESCRIPTION
**Pull request by tomgco**

### CODE REVIEW

**Comment by lennym** [comment]
"...with this one weird trick"

**Comment by nelsonic** [comment]
@lennym are you investigating why the build is failing on `master` ?

**Comment by lennym** [comment]
It looks to be because the websocket server (a.k.a numo-labs/graphql-backchannel) was playing up. Builds are green now.

**Comment by lennym** [comment]
@tomgco You score a 👎  for starting a branch name with a `m` and so breaking my console tab completion of `master`.

😠

**Pull request merged**
