### PR TITLE
Landing analytics

### PR DESCRIPTION
**Pull request by Kumjami**
When a user reach isearch, only if he is coming from spies.dk we track his data.

### CODE REVIEW

**Comment by nelsonic** [comment]
@Kumjami / @nikhilaravi do we still nee to change _both_ `src/index.html` and `src/index.template.html` ...? they _appear_ to be the same...?

**Comment by Kumjami** [comment]
@nelsonic the [production webpack config](https://github.com/numo-labs/isearch-ui/blob/master/webpack.production.config.js#L50) file is using the template one. 
I did't even though about why do we have the .template one. But I think it's a good question. @nikhilaravi could probably clarify this.

**Comment by nikhilaravi** [comment]
@Kumjami @nelsonic wepback adds a hash to the filename of the bundle and so the index template is used to create an index file which has a script tag referring to the correct bundle. 

For development when we run the webpack dev server we need the index.html file. 

So yes we do need both files and any scripts for analytics need to be added to both.

**Comment by Kumjami** [comment]
Good to know. Thanks @nikhilaravi :ok_hand:

**Comment by nelsonic** [comment]
OK. merging. 👍

**Pull request merged**
