### PR TITLE
onEnter

### PR DESCRIPTION
**Pull request by jackcarlisle**
* removes page refresh when enter is pressed

### CODE REVIEW

**Comment by nelsonic** [comment]
@jackcarlisle to keep CodeCov happy, would you mind adding another test to this PR? :wink:

**Comment by jackcarlisle** [comment]
@nelsonic will do!

**Comment by jackcarlisle** [comment]
@nelsonic coverage should look a little better now!

**Comment by nelsonic** [comment]
@jackcarlisle nice one. :+1: 
hope you have a great weekend!

**Pull request merged**
