### PR TITLE
Uploads a version file on deploy to ci or prod.

### PR DESCRIPTION
**Pull request by tomgco**

### CODE REVIEW

**Comment by nelsonic** [comment]
As discussed. looks good. 
_However_ `semistandard` isn't happy:
isearch-semistandard-fail
https://codeship.com/projects/140431/builds/16287413

**Comment by nelsonic** [comment]
Merging. 🚀

**Comment by tomgco** [comment]
> Merging.

Apologies, didn't run the tests.

**Comment by nelsonic** [comment]
It _works_. that's what matters. 😉  🎉

**Pull request merged**
