### PR TITLE
Filters

### PR DESCRIPTION
**Pull request by nikhilaravi**
Adds functionality to:

- add a search string as a tag
- store a local list of all the returned items
- filter the local list as well as launch a new query when a new search term is input
- merge the returned items into the displayed items list and remove duplicates
- added logic for filter tiles - can now filter by amenity on the front end (filtering by country is not yet available)

- added tests for the reducer
- added some tests for the actions 

### TODO: 

- How to test polling behaviour in redux actions!

### CODE REVIEW

**Comment by nikhilaravi** [comment]
@nelsonic I need to update all the tests as have added quite a lot of new functionality!!

**Comment by nelsonic** [comment]
@nikhilaravi do you have time to help resolve the CI ?

**Comment by nikhilaravi** [comment]
@nelsonic there's a pull request for the gql here: https://github.com/numo-labs/lambda-numo-graphql/pull/55/files

**Comment by nelsonic** [comment]
@nikhilaravi please ping me when the merge conflicts are resolved for this branch. thanks! :+1:

**Comment by nelsonic** [comment]
@nikhilaravi looks promising. ping me when tests pass (*tomorrow morning...*) 😉

**Comment by nikhilaravi** [comment]
@nelsonic I've fixed the tests and added functionality to filter again when a tag is removed!! Coverage is a bit low because I haven't yet figured out how to test polling in the search actions... so these actions aren't being tested

**Comment by nelsonic** [comment]
Looks good. 👍

**Pull request merged**
