### PR TITLE
Updates gulp script to create and push tag on gulp prod deploy

### LINKED ISSUE #319: Automatically create and upload a new tag when deploying to production
Based on the version in the package.json create a git tag and push it to remote when the gulp `prod:deploy` task is called.

### PR DESCRIPTION
**Pull request by nikhilaravi**
From the tag, the release still needs to be created manually - as far as I am aware, releases can only be created using the Github API.

fixes #319

### CODE REVIEW

**Comment by nelsonic** [comment]
@nikhilaravi might be worth adding a paragraph to the Readme for how this works or a link to an issue where this was discussed as a comment next to the code.
It _looks_ like it works but it _might_ not be _obvious_ to our future-selves... ❓

**Comment by nikhilaravi** [comment]
@nelsonic sure I will do that.

**Comment by nikhilaravi** [comment]
@nelsonic I've updated the readme with notes.

**Comment by lennym** [comment]
It would probably be good to have an alias for the gulp tasks in the npm scripts so we didn't need to force a global dependency.

There [seems to be a `deploy` script already](https://github.com/numo-labs/isearch-ui/blob/21d88b36f6f67ecfe91f84a365bdd79c76a90dce/package.json#L22) but it points at a non-existent gulp task from what I can work out.

**Comment by nelsonic** [comment]
@lennym which _global_ dependency are you referring to?
gulp is listed in [`package.json#L62`](https://github.com/numo-labs/isearch-ui/blob/a130d76987b9b5875e7dff9a2a11bad56589a443/package.json#L62) 
I haven't installed it _globally_ and the deploy (gulp) script still works... (_sorry if I'm being a bit thick..._)

**Comment by nelsonic** [comment]
@nikhilaravi thanks for adding those notes. 🎉

**Comment by lennym** [comment]
@nikhilaravi If you can run `gulp deploy` from the command line then *at some point in time* you will have installed it globally. Otherwise you get an error like `bash: gulp: command not found`.

**Comment by lennym** [comment]
I have created #320 to remove the need for global gulp.

**Pull request merged**
