### PR TITLE
checklist, book text and overlaping text fixed

### PR DESCRIPTION
**Pull request by Kumjami**
3 first checkpoints of the **Hotel page** section of https://github.com/numo-labs/isearch-ui/issues/118#issuecomment-218127818

### CODE REVIEW

**Comment by nelsonic** [comment]
@Kumjami can you please run semistandard (`npm run lint`) *before* committing?
see: https://codeship.com/projects/140431/builds/14678841

**Comment by Kumjami** [comment]
yes, sorry, I completely forgot

**Comment by nelsonic** [comment]
@Kumjami Also, now that the build is passing on CodeShip, the CodeCov report highlights the fact that additional lines of code have been added in the PR but no additional tests (*i.e. test coverage has gone down...*) please add a test for the code you have added. thanks.

**Comment by Kumjami** [comment]
@nelsonic The thing is that I've just removed code, but I will increase it.

**Comment by nelsonic** [comment]
@Kumjami understood, thanks.

**Pull request merged**
