### PR TITLE
Home page fix

### PR DESCRIPTION
**Pull request by nikhilaravi**
- Adds temp fix for showing search bar inside the header for desktop view and fixes sizes of header image and search bar

### CODE REVIEW

**Comment by nelsonic** [comment]
good plan. please deploy to 0.13 thanks. 👍

**Comment by nelsonic** [comment]
@nikhilaravi please fix semistandard after lunch. 👍

**Comment by nikhilaravi** [comment]
@nelsonic The tests should now all pass! Please merge once passed! :)

**Comment by nelsonic** [comment]
Sweet! 🍭

**Pull request merged**
