### PR TITLE
Data layer

### PR DESCRIPTION
**Pull request by jackcarlisle**
* adds the datalayer to the yesNoFilter

### CODE REVIEW

**Comment by nelsonic** [comment]
@jackcarlisle CI fails because it *thinks* `dataLayer` is `undefined` ...

**Comment by nelsonic** [comment]
I am merging this PR on the basis that it adds the *essential* google analytics tracking we need for the demo. it makes me 😢  that the coverage goes down but we know what to do to "*fix*" that on Monday. 👍

**Comment by jackcarlisle** [comment]
cool 👍

**Comment by nelsonic** [comment]
thanks a *bunch* for your help with this @jackcarlisle & @nikhilaravi ✅

**Comment by jackcarlisle** [comment]
@nelsonic you're welcome! anytime

**Pull request merged**
