### PR TITLE
warning box

### LINKED ISSUE #475: Some style fixes for warning box
### Screen Shot
[Mobile](http://zpl.io/ZfYaxG)
[Desktop](http://zpl.io/1AIH2l)

### Further Information
Warning box should be as wide as the tiles container.
Font-size should be ≈ 14px

See Zeplin links for more style information.

### PR DESCRIPTION
**Pull request by Kumjami**
closes #475 

#### ready for review

### CODE REVIEW

**Comment by lennym** [comment]
Does this also address the issue in #475 about the width of the warning box?

**Comment by jackcarlisle** [comment]
@Kumjami is the warning message at the correct width?

**Comment by Kumjami** [comment]
actually working on it, sorry

**Comment by jackcarlisle** [comment]
nice 👍  merging

**Pull request merged**
