### PR TITLE
Clicking in a hotel spies.dk link now creates an analytics event

### PR DESCRIPTION
**Pull request by Kumjami**
Need to specify `dimension11` and `dimension12` content

### CODE REVIEW

**Comment by nelsonic** [comment]
@Kumjami please assign when ready for review. 👍

**Comment by Kumjami** [comment]
I will do it, I'm just waiting Philip clarifications (he is having meetings and discussions to get clarifications).

**Comment by Kumjami** [comment]
@nelsonic Need to merge https://github.com/numo-labs/lambda-ne-classic-package-provider/pull/99 and after that this can be merged too.

**Comment by nelsonic** [comment]
@Kumjami looks good. 👍

**Pull request merged**
