### PR TITLE
Refactor grid

### PR DESCRIPTION
**Pull request by nikhilaravi**
Refactors grid component and creates mock data file. 

https://tc-jira.atlassian.net/browse/ISEARCH-188

### CODE REVIEW

**Comment by nelsonic** [comment]
Looks good @nikhilaravi :+1:

**Comment by nelsonic** [comment]
@jackcarlisle unless you have any comments/notes I'm happy to merge this...

**Comment by jackcarlisle** [comment]
@nelsonic just having a quick look now

**Comment by jackcarlisle** [comment]
@nelsonic looks good to me! :+1:

**Pull request merged**
