### PR TITLE
Support an automatic search tag based on query string

### PR DESCRIPTION
**Pull request by lennym**
If the search is loaded with a `?search=<term>` query string parameter then do an autocomplete lookup based on the search term provided, and if a result is returned then use that as the "default" search term on initial load instead of the "Top inspiration" tag.

### CODE REVIEW

**Comment by lennym** [comment]
Code complete. Unit tests imminent.

**Comment by lennym** [comment]
Ready to go. 

Closes #316

**Comment by nelsonic** [comment]
Good idea @lennym 👍

**Comment by lennym** [comment]
I can't take any credit for the idea - that was all @jruts work - #316

**Comment by nelsonic** [comment]
Yeah, we all know @jruts is the _brains_ behind this whole operation... 😉 
brains

**Pull request merged**
