### PR TITLE
Nightwatch automated browser testing

### PR DESCRIPTION
**Pull request by nelsonic**
Implemented Nightwatch testing in (_hopefully_) the simplest way. `npm install && npm test` ...
Still going to add another test scenario. but if anyone wants to track progress here it is.

https://github.com/numo-labs/isearch-ui/issues/312

If anyone wants access to Saucelabs, let me know, I will FWD your email address to the admin so she can add you to the account.

### CODE REVIEW

**Comment by tomgco** [comment]
Any update on this @nelsonic, I really want to get this merged in, and get it up and running.

**Comment by nelsonic** [comment]
@tomgco we can ship this as is. it already runs through 2 common scenarios.

**Comment by nelsonic** [comment]
@jackcarlisle do you have time to review this today?

**Comment by jackcarlisle** [comment]
@nelsonic I can review this now!

**Comment by jackcarlisle** [comment]
Looks good to me 👍 merging

**Comment by krosti** [comment]
👍

**Pull request merged**
