### PR TITLE
Analytics

### PR DESCRIPTION
**Pull request by Kumjami**
Analytics data regarding clicks and visits to packages, articles and tiles.

### CODE REVIEW

**Comment by nelsonic** [comment]
@Kumjami please merge master into the Analytics branch and resolve any merge conflicts then assign this PR to me. thanks! 👍

**Comment by nelsonic** [comment]
@Kumjami assign when ready. 👍

**Comment by Kumjami** [comment]
I think it's better to wait until routing working again. This is why I didn't ping about it.

**Comment by nelsonic** [comment]
agreed. ok. so https://github.com/numo-labs/isearch-ui/issues/168 next ?

**Comment by nelsonic** [comment]
@Kumjami what do we need to get Routing working today?

**Comment by Kumjami** [comment]
@nelsonic to be able to merge this https://github.com/numo-labs/isearch-ui/pull/176
This would made us to be able to grab "static" data and print it.
Right now I just uploaded some testing data and the json files paths are hardcoded, and it seems to work as it should.
So after removing this hardcode paths, It should work as far as the structure in json files is the same.

**Comment by nelsonic** [comment]
@Kumjami from today each `item` (package/article) returned to the client via websockets will contain a `url` see: https://github.com/numo-labs/lambda-ne-classic-package-provider/pull/71/files#r65325279

**Comment by nelsonic** [comment]
@Kumjami I will merge this as soon as the front-end is working again... @tomgco is investigating the WebSockets ... 🔜

**Comment by nelsonic** [comment]
@Kumjami please merge master into this branch to get the latest changes.
resolve any merge conflicts and re-assign back to me. thanks! 👍

**Comment by nelsonic** [comment]
@Kumjami thanks for updating this! really excited to get it into `master`! 👍

**Pull request merged**
